language: go
sudo: false
go:
  - 1.9.x

git:
  depth: 3

install:
  - go get "github.com/ConfWatch/confwatchd"
  - cd "${GOPATH}/src/github.com/ConfWatch/confwatchd"
  - make

script:
  - ./confwatchd -config dev-config.json -seed "${TRAVIS_BUILD_DIR}/"

